### ISSUE TITLE
虚拟主播列表更新频率？

### ISSUE THREAD

**Issue by wudifeixue** [eric2788/ddstats.ericlamm.xyz#2]
Eric你好，想知道多久会从vtbs.moe那边更新一次数据，我大概搜了下

一周前https://github.com/dd-center/vdb
添加的新数据也还没有出现在https://ddstats.ericlamm.xyz
所以比较好奇你这边是多久更新一下

**Comment by eric2788** [comment]
几分钟吧
可能没有成功启动监听？
目前云服务器掉线还是挺严重的

**Comment by wudifeixue** [comment]
那确实没成功的样子，举几个找不到的个例：
瀬兎一也_Official
个人空间: 
https://space.bilibili.com/1006140314
直播间: 
https://live.bilibili.com/24921679

宴宁ccccc
个人空间: 
https://space.bilibili.com/14897804
直播间: 
https://live.bilibili.com/7953876

花园花玲
个人空间: 
https://space.bilibili.com/7966
直播间: 
https://live.bilibili.com/597450

**Comment by eric2788** [comment]
![image](https://user-images.githubusercontent.com/6276840/167860309-e38e8013-ec6b-42b0-96db-51cc71dcbeb8.png)
問題應該是這個

**Comment by wudifeixue** [comment]
喔～发现了问题好啊

**Comment by eric2788** [comment]
> 

看了看，返回格式沒有變化，而且之前也能正常運作，所以大概推斷可能是請求太多被攔截的問題

**Comment by eric2788** [comment]
現在你上面說的應該全有了
